### PR TITLE
Feature: Command line interface for using canuvit

### PR DESCRIPTION
**Pull request by k-sriram**
This enables using `canuvit` from the command line. I have used click to implement the interface. Its usage should be self-explanatory after reading about in the the README. There's also some other additions like populating the requirements.txt file.

### CODE REVIEW

**Comment by prajwel** [comment]
Thank you for this fantastic feature and I am quite excited to see a pull request! I have a few comments, and can you please consider discussing them? This is my first code review too, so I hope I am doing this correctly. 

* In the `setup.cfg` file, the line `packages = find:` should be able to discover all packages and sub-packages automatically. I prefer to keep the package as per the new Python packaging guidelines (https://packaging.python.org/tutorials/packaging-projects/). So can we avoid the `requirements.txt` and `setup.py` files? Is there a specific benefit that I am not aware of? 
* I think `canuvit` should be compatible with older versions of the required packages. Most of the codebase was written 3-4 years back and developed on Python2.7. Then few changes were made to make it work in Python3. Therefore I suggest that we may remove the `install_requires` option. For `click`, I think the ` python_requires = >=3.6` should ensure the version is above 8.

**Comment by k-sriram** [comment]
We can definitely remove the `setup.py`. I only added it because installing packages in editable mode still can't be done with `pyproject.toml`. Editable mode is just a nice quality of life feature for developers and end users will never need it.

About `install_requires`: This package requires at least some version of `numpy` et al. to be installed for it to work, so we can't simply skip it. The best thing to do would be to find the oldest version of these libraries with which this package runs and put that version in `install_requires`. For now I put whatever was the current version in January 2017 and tested that it works. Except for `astropy` as they have added plenty of new features in recent times and I didn't know if you used any of them in your code.

I am up to figuring out what would be the earliest version of each package. It might only take a couple of hours.

About `requirements.txt`, I have never tried to write without it as everything I have read about packaging in python told me that it is better to have it. It makes pip work much better.

I could've also written the command line interface without `click`. Python natively has `argparse`. I just preferred `click` as there is no clean way to tell `argparse` that negative numbers are not options (as both of them begin with a `-`) and declination is negative half the time.

**Comment by k-sriram** [comment]
> * the line `packages = find:` should be able to discover all packages and sub-packages automatically.

You misunderstood what `packages = find:`  does. It doesn't look for packages required by your package. In this field you list out what all packages are provided by you. So another valid value for this field would have been
```ini
[options]
packages = canuvit
package_dir = 
    =src
```
What `packages = find:` does is look inside the `src` (defined in `[options.packages.find] where`) folder for packages. Since it has a folder `canuvit` with an `__init__.py` file it recognizes it as a package.

`[options] packages` tells the install script about the packages you provide, not the packages you require.

**Comment by prajwel** [comment]
Thank you for pointing out my mistake about `find:`. I noticed that you have also corrected my license. I am merging this to the main.

**Comment by k-sriram** [comment]
Can you revert the merge? I can incorporate some of the things you mentioned. I looked through the dependencies to find the minimal version of the dependencies that still work.

Also the `requirements.txt` file is not strictly required. I am looking through stackoverflow to look for best practices here.

I had also bumped the version number to 0.3.0. If you had any other scheme in mind tell and want some other version number tell me.

**Comment by prajwel** [comment]
I think the additional changes can be a new pull request. I don't want to mess with git too much 😄, so let us keep it simple. By the way, `re.Pattern` was introduced in Python3.7. Shall we suppress `CheckREParamType` for 3.6? Or is there another way? 

I am sorry that I didn't understand the [WIP] tag you had kept on the pull request. Should not have gone too hasty!

The version is now at 0.3.0, depending on the changes, you can suggest a new version.

**Comment by k-sriram** [comment]
In many repositories, they have some feature which lets you not be able to merge pull requests if they have a WIP in the title. I think it is one of those paid features. Anyway I will make a new PR.

**Pull request merged**
